apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        env:
          - name: VAR1
            value: "hola" 
        resources:
            limits:
              cpu: 100m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 300Mi
        image: nginx:1.7.9
        ports:
        - containerPort: 80